#version: '2'
#services:
neo4j:
  image: neo4j:latest
  #network_mode: host
  restart: always
  environment:
    - NEO4J_AUTH=neo4j/braf1913;
  cap_add:
    - SYS_RESOURCE
  ports:
    - "7474:7474"
    - "7473:7473"
    - "7687:7687"
  volumes:
    - /Users/p491748/projects/vargraph/graphdbs/reactome/datafordocker:/data

app:
  image: vargraph
  ports:
    - "5000:5000"