version: '3.7'
services:
  neo4j:
    image: us.gcr.io/psjh-235004/neo4j_reactome
    #network_mode: host
    restart: always
    environment:
      - NEO4J_AUTH=neo4j/braf1913
    cap_add:
      - SYS_RESOURCE
    ports:
      - "7474:7474"
      - "7473:7473"
      #- "172.17.0.1:7687:7687"
      - "7687:7687"
    #volumes:
    #  - /Users/p491748/projects/vargraph/graphdbs/reactome/datafordocker:/data
  
  app:
    #image: .
    build: .
    environment:
      - REACTOME_PWD
      - REPORTERUNAME
      - REPORTERPWD
      - VARGRAPHPWD
    ports:
     # - "172.17.0.1:5001:5000"
      - "5001:5000"
    depends_on:
      - "neo4j"
#    command: ["./wait-for-it.sh", "neo4j:7474", "--", "FLASK_APP=flaskfe.py","python", "-m", "flask", "run" ]
    restart: always
    volumes:
      - .:/vargraph 
